### ISSUE TITLE
Project fairly quiet

### ISSUE THREAD

**Issue by MaineC** [coreos/issue-sync#53]
Looking at commits, issues and pull requests this repository looks fairly quiet. Given that this lives in the coreos org, am I right in assuming that this project at the moment is no longer used/ maintained by it's original authors?

**Comment by unformatt** [comment]
Save yourself the pain of wrangling the Jira API and use a service to do this syncing, like [BoardGenius.io](https://boardgenius.io).

**Comment by squat** [comment]
Hi @MaineC you are correct that this project is no longer being actively used internally by the CoreOS team. After Red Hat's acquisition of CoreOS, our workflows changed significantly and we switched issue tracking systems (a few times :p). That said, I know that some community members have continued to use the project since that time.

**Comment by MaineC** [comment]
Thanks for the feedback @squat
